version: 2.1
jobs:
  lint-theme:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    environment:
      - THEME_PATH: "vendor/snowdog/theme-frontend-alpaca"
      - CONFIG_PATH: "vendor/snowdog/theme-frontend-alpaca/.circleci/frontools/config"
    steps:
      - run: sudo apt-get install rsync
      - checkout
      - run: mkdir -p $THEME_PATH
      - run: rsync -r --delete . $THEME_PATH
      - run: cp "$THEME_PATH/composer.json" .
      - run: composer update --no-dev --no-interaction --prefer-dist --no-progress --ignore-platform-reqs
      - run: mkdir -p dev/tools/frontools
      - run: cp -r $CONFIG_PATH dev/tools/frontools
      - run: cd vendor/snowdog/frontools && yarn && yarn setup
      - run: cd tools && yarn inheritance
      - run: cd tools && yarn sasslint --ci
      - run: cd tools && yarn styles --ci --pipeline
      - run: cd tools && yarn csslint --ci
  deploy-components:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    environment:
      - THEME_PATH: "vendor/snowdog/theme-frontend-alpaca"
      - NOW_SCOPE: "snowdog"
      - NOW_PROJECT: $CIRCLE_PROJECT_REPONAME
      - NOW_URL: https://${CIRCLE_PROJECT_REPONAME}.now.sh
    steps:
      - checkout
      - run: cd Snowdog_Components && yarn
      - run: cd Snowdog_Components && yarn build --ci
      - run: cd Snowdog_Components && sudo npm install --global --unsafe-perm --silent now@16.7
      - run: cd Snowdog_Components && DEPLOYMENT_URL=$(now --force --token ${NOW_TOKEN} --scope ${NOW_SCOPE} --name ${NOW_PROJECT} `if [ $BUILD_ENV ]; then echo "--build-env $BUILD_ENV"; fi` `if [ $ENV ]; then echo "--env $ENV"; fi` `if [ $PRODUCTION ]; then echo "--prod"; fi`)
      - run: cd Snowdog_Components && now --token ${NOW_TOKEN} --scope ${NOW_SCOPE} alias set ${DEPLOYMENT_URL} ${NOW_URL}

workflows:
  theme:
    jobs:
      - lint-theme
  components:
    jobs:
      - deploy-components
